### ISSUE TITLE
Create a tagged release

### ISSUE THREAD

**Issue by mdehollander** [HKU-BAL/megagta#1]
Would it be possible to create a release, like 0.1-alpha? I am trying to create a bioconda package and it would help to have a release point. Using the zip is missing the RDP part. More info of my attempt: https://github.com/bioconda/bioconda-recipes/pull/2440

**Comment by voutcn** [comment]
Sure. Please let us know if you need more help.

**Comment by voutcn** [comment]
Please be careful about the path of HMMER & UCHIME in `bin/post_proc.sh`
